src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $category_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_url = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_active = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?int $display_order = null;

    #[ORM\ManyToMany(targetEntity: Product::class, mappedBy: 'categories')]
    private Collection $products;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tagline = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $summary = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_main_category = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $video_url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $page_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getCategoryName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(?string $category_name): static
    {
        $this->category_name = $category_name;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): static
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getDisplayOrder(): ?string
    {
        return $this->display_order;
    }

    public function setDisplayOrder(?string $display_order): static
    {
        $this->display_order = $display_order;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->addCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            $product->removeCategory($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTagline(): ?string
    {
        return $this->tagline;
    }

    public function setTagline(?string $tagline): static
    {
        $this->tagline = $tagline;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(?string $summary): static
    {
        $this->summary = $summary;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isIsMainCategory(): ?bool
    {
        return $this->is_main_category;
    }

    public function setIsMainCategory(?bool $is_main_category): static
    {
        $this->is_main_category = $is_main_category;

        return $this;
    }

    public function getVideoUrl(): ?string
    {
        return $this->video_url;
    }

    public function setVideoUrl(?string $video_url): static
    {
        $this->video_url = $video_url;

        return $this;
    }

    public function getPageTitle(): ?string
    {
        return $this->page_title;
    }

    public function setPageTitle(?string $page_title): static
    {
        $this->page_title = $page_title;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $product_name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?float $price = null;

    #[ORM\Column(nullable: true)]
    private ?float $discount_price = null;

    #[ORM\Column(nullable: true)]
    private ?float $stock_quantity = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $images = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $rating = null;

    #[ORM\Column(nullable: true)]
    private ?int $number_of_ratings = null;

    #[ORM\Column(nullable: true)]
    private ?bool $availability = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $features = null;

    #[ORM\Column(nullable: true)]
    private ?float $weight = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_featured = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_new = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_bestseller = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_onsale = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_added = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OrderItem::class)]
    private Collection $orderItems;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductReview::class)]
    private Collection $productReviews;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: CartItem::class)]
    private Collection $cartItems;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductDisplay::class)]
    private Collection $productDisplays;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductImage::class)]
    private Collection $productImages;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $box_size = null;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'products')]
    private Collection $categories;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $video_link = null;

    #[ORM\ManyToMany(targetEntity: ProductColor::class, mappedBy: 'product')]
    private Collection $productColors;

    #[ORM\ManyToMany(targetEntity: DiscountCode::class, mappedBy: 'product')]
    private Collection $discountCodes;

    private $latestDiscountCode = null;

    public function __construct()
    {
        $this->orderItems = new ArrayCollection();
        $this->productReviews = new ArrayCollection();
        $this->cartItems = new ArrayCollection();
        $this->productDisplays = new ArrayCollection();
        $this->productImages = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->productColors = new ArrayCollection();
        $this->discountCodes = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getProductName();
    }

    public function getLatestDiscountCode(): ?DiscountCode
    {
        $currentDate = new \DateTimeImmutable();
        
        // Criteria to filter discountCodes based on validity dates and isActive flag
        $criteria = Criteria::create()
            ->andWhere(Criteria::expr()->lte('validity_start_date', $currentDate))
            ->andWhere(Criteria::expr()->gte('validity_end_date', $currentDate))
            ->andWhere(Criteria::expr()->eq('is_active', true))
            ->orderBy(['validity_end_date' => Criteria::DESC]) // Sort by validity_end_date in descending order
            ->setMaxResults(1); // Get only one result which is the latest
        
        // Apply criteria to discountCodes collection
        $filteredDiscountCodes = $this->discountCodes->matching($criteria);
        
        // If there are any matching discount codes, return the first one
        if ($filteredDiscountCodes->count() > 0) {
            $this->latestDiscountCode = $filteredDiscountCodes->first();
            return $filteredDiscountCodes->first();
        }
        
        return null; // No matching discount code found
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    public function setProductName(?string $product_name): static
    {
        $this->product_name = $product_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDiscountPrice(): ?float
    {
        return $this->discount_price;
    }

    public function setDiscountPrice(?float $discount_price): static
    {
        $this->discount_price = $discount_price;

        return $this;
    }

    public function getStockQuantity(): ?float
    {
        return $this->stock_quantity;
    }

    public function setStockQuantity(?float $stock_quantity): static
    {
        $this->stock_quantity = $stock_quantity;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(?string $images): static
    {
        $this->images = $images;

        return $this;
    }

    public function getRating(): ?string
    {
        return $this->rating;
    }

    public function setRating(?string $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    public function getNumberOfRatings(): ?int
    {
        return $this->number_of_ratings;
    }

    public function setNumberOfRatings(?int $number_of_ratings): static
    {
        $this->number_of_ratings = $number_of_ratings;

        return $this;
    }

    public function isAvailability(): ?bool
    {
        return $this->availability;
    }

    public function setAvailability(?bool $availability): static
    {
        $this->availability = $availability;

        return $this;
    }

    public function getFeatures(): ?string
    {
        return $this->features;
    }

    public function setFeatures(?string $features): static
    {
        $this->features = $features;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): static
    {
        $this->weight = $weight;

        return $this;
    }

    public function isIsFeatured(): ?bool
    {
        return $this->is_featured;
    }

    public function setIsFeatured(?bool $is_featured): static
    {
        $this->is_featured = $is_featured;

        return $this;
    }

    public function isIsNew(): ?bool
    {
        return $this->is_new;
    }

    public function setIsNew(?bool $is_new): static
    {
        $this->is_new = $is_new;

        return $this;
    }

    public function isIsBestseller(): ?bool
    {
        return $this->is_bestseller;
    }

    public function setIsBestseller(?bool $is_bestseller): static
    {
        $this->is_bestseller = $is_bestseller;

        return $this;
    }

    public function isIsOnsale(): ?bool
    {
        return $this->is_onsale;
    }

    public function setIsOnsale(?bool $is_onsale): static
    {
        $this->is_onsale = $is_onsale;

        return $this;
    }

    public function getDateAdded(): ?\DateTimeInterface
    {
        return $this->date_added;
    }

    public function setDateAdded(?\DateTimeInterface $date_added): static
    {
        $this->date_added = $date_added;

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): static
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setProduct($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): static
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getProduct() === $this) {
                $orderItem->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ProductReview>
     */
    public function getProductReviews(): Collection
    {
        return $this->productReviews;
    }

    public function addProductReview(ProductReview $productReview): static
    {
        if (!$this->productReviews->contains($productReview)) {
            $this->productReviews->add($productReview);
            $productReview->setProduct($this);
        }

        return $this;
    }

    public function removeProductReview(ProductReview $productReview): static
    {
        if ($this->productReviews->removeElement($productReview)) {
            // set the owning side to null (unless already changed)
            if ($productReview->getProduct() === $this) {
                $productReview->setProduct(null);
            }
        }

        return $this;

templates/default/about.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} 
{{ leogout_seo() }} 
<style>
    h2{
        font-size: 26px;
        text-transform: capitalize;
        
    }
    p, ul, ol, div{
      font-size:16px!important;
      line-height:1.5;
      text-align: left;
    }

    ul, ol {
        list-style-type: disc;
    }
    
</style>
{% endblock %}
{% block page %}
      <section class="breadcrumbs-custom">
        <div class="parallax-container" data-parallax-img="/site/images/baby-blossom-all-products-banner.jpg">
          <div class="breadcrumbs-custom-body parallax-content">
            <div class="container">
              <h1 class="breadcrumbs-custom-title">About Us - Our Ingredients</h1>
            </div>
          </div>
        </div>
        <div class="breadcrumbs-custom-footer">
          <div class="container">
            <ul class="breadcrumbs-custom-path">
              <li><a href="{{ path('app_default') }}">Home</a></li>
              <li><a href="#">Pages</a></li>
              <li class="active">About Us - Our Ingredients</li>
            </ul>
          </div>
        </div>
      </section>
      <!-- About Us - Our Ingredients-->
      <section class="section section-xxl bg-default text-md-left">
        <div class="container">
          <div class="row">
            <div class="col-lg-10 col-xl-8">
              <!-- Terms list-->
              {{ about.content|replace({'.' : '.<br><br>'})|raw }}
            </div>
          </div>
        </div>
      </section>
{% endblock %}      

templates/default/category_landing.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} {{ leogout_seo() }} 
  <style>
    h2 {
      font-size:32px!important;
    }
    h3 {
      font-size:26px!important;
    }
    h4 {
      font-size:20px!important;
    }
    h2,h3,h4 {
      text-transform:capitalize!important;
    }
    .container ul {
      margin-bottom:1rem!important;
      margin-top:14px!important;
    }
  </style>
{% endblock %}
{% block page %}

      <section class="section parallax-container section-custom-1" data-parallax-img="{{ asset('site/images/uploads/' ~ category.imageUrl ) }}">
        <div class="parallax-content section-md text-left section-first-2 title-parallax">
          <div class="container">
            <div class="box-info-renee-decor"></div>
            <h1 class="box-info-renee-title wow fadeScale" style="color:white;">{{ category.pageTitle }}</h1>
            <div class="box-info-renee-subtitle wow fadeInLeft" style="color:white;">{{ category.tagline }}</div>
            <p class="box-info-renee-text wow fadeInRight" style="color:white;">{{ category.summary }}</p>
            <a class="link-classic box-info-renee-link wow fadeInUp" style="color:white;" href="#products">Shop Now</a>
          </div>
        </div>
      </section>
      {% set customDelimiter = '</p>' %}
      {% set paragraphs = category.description|raw|split(customDelimiter) %}
      {% set firstThree = paragraphs|slice(0, 3) %}
      {% set remaining = paragraphs|slice(3) %}

      <section class="section section-sm section-last bg-default text-left">
        <div class="container">
          <div class="row">
            {% if category.videoUrl|length > 3 %}
            <div class="col-md-6">
              <h2>{{ category.categoryName }} Video</h2>
              <p>{{ category.videoUrl|raw }}</p>
            </div>
            {% endif %}
            <div class="col-md-6">
              <h2 class="title-style-9 wow fadeInRight">Best Affordable {{ category.categoryName }} in Nairobi, Kenya</h2>
              <div class="first-three-paragraphs">
                {% for paragraph in firstThree %}
                {% set full_paragraph = paragraph ~ customDelimiter %}
                  {{ full_paragraph|raw }}
                {% endfor %}
              </div>
              <div class="group-md group-middle"><a class="button button-lg button-primary-2 button-zakaria" href="#products">Shop Now</a><a class="button button-lg button-default-outline button-zakaria" href="#remaining">Read More</a></div>
            </div>
          </div>
        </div>
      </section>
       
      <!-- Top Products-->
      <section id="products" class="section section-xxl bg-gray-1">
        <div class="container">
          <h2 class="title-style-8 wow fadeScale">{{ category.categoryName }} Products</h2>
          <div class="isotope-wrap">
            <div class="isotope-filters">
              <button class="isotope-filters-toggle button button-sm button-icon button-icon-right button-default-outline" data-custom-toggle=".isotope-filters-list" data-custom-toggle-hide-on-blur="true"><span class="icon mdi mdi-chevron-down"></span>Filter</button>
            </div>
            <div class="row row-30 row-lg-50 isotope">
            {% for product in products %}
              <div class="col-sm-6 col-md-4 col-lg-3 isotope-item" data-filter="{% for category in product.categories %} {{ category|replace({' ': '-'}) ~ ' ' }} {% endfor %}">
                <!-- Product-->
                <article class="product product-2 wow fadeInRight">
                  <div class="product-body">
                    <div class="product-figure"><a href="{{ path('product_show', {'product_slug': product.slug }) }}"><img src="{{ asset('site/images/products/' ~ product.images ) }}" alt="" width="144" height="199"/></a>
                    </div>
                    <h5 class="product-title"><a href="{{ path('product_show', {'product_slug': product.slug }) }}">{{ product.productName }}</a></h5>
                    <div class="product-price-wrap">
                      <div class="product-price">KSh {{ product.price }}</div>
                    </div>
                  </div>
                  <div class="product-button-wrap">
                    <div class="product-button"><a class="button button-gray-14 button-zakaria fl-bigmug-line-search74" href="{{ path('product_show', {'product_slug': product.slug }) }}"></a></div>
                    <div class="product-button"><form id="prodForm-{{product.id}}"><input type="hidden" id="quantity_{{product.id}}" value="1"><button style="margin-top:0" name="cartProd_{{product.id}}" id="cartProd_{{product.id}}" class="button button-primary-2 button-zakaria fl-bigmug-line-shopping202" type="button"></button></form></div>
                  </div>
                </article>
              </div>
            {% endfor %}

            </div>
          </div>
        </div>
      </section>
      
      <!-- About Us-->
      <section id="remaining" class="section section-xxl section-inset-3 text-sm-left bg-gray-13 bg-image" style="padding-bottom:200px;background-image: url({{asset('site/images/bg_with_logo.png') }});">
        <div class="container">
          <div class="row">
            <div class="col-sm-9 col-md-9 col-lg-9 box-about">
              <h2>More about {{ category.categoryName }}</h2>
              <div class="remaining-paragraphs">
                {% for paragraph in paragraphs|slice(3) %}
                {% set full_paragraph = paragraph ~ customDelimiter %}
                  {{ full_paragraph|raw }}
                {% endfor %}
              </div>            
            </div>
          </div>
        </div>
      </section>

      <!-- Calls to action-->
      <section class="section section-xl text-md-left bg-image" style="background-image: url({{ asset('site/images/Parallax-calendula-bg-1920x402.jpg') }});">
        <div class="container">
          <div class="row row-30 align-items-center justify-content-md-between">
            <div class="col-md-6 col-lg-8">
              <h3 class="text-spacing-100">Get 10% Off On Every Repeat Purchase</h3>
              <h6 class="font-weight-light">Every time we notice that you've come back for more, we give you 10% discount..</h6>
            </div>
            <div class="col-md-auto"><a class="button button-lg button-shadow-2 button-primary-2 button-zakaria" href="{{ path('app_shop')}}">Shop Now</a></div>
          </div>
        </div>
      </section>

      <!-- Gallery-->
      <section class="section section-sm section-last bg-default">
        <div class="container">
          <div class="row no-gutters" data-lightgallery="group">
            <div class="col-6 col-sm-4 col-lg-3"><a class="thumbnail-minimal" href="{{ asset('site/images/uploads/instagram/Babyblossom-' ~ category.slug ~ '-1.jpg') }}" data-lightgallery="item"><img src="{{ asset('site/images/uploads/instagram-sm/bblossom-' ~ category.slug ~ '-1.jpg') }}" alt="" width="290" height="219"/></a></div>
            <div class="col-6 col-sm-4 col-lg-3"><a class="thumbnail-minimal" href="{{ asset('site/images/uploads/instagram/Babyblossom-' ~ category.slug ~ '-2.jpg') }}" data-lightgallery="item"><img src="{{ asset('site/images/uploads/instagram-sm/bblossom-' ~ category.slug ~ '-2.jpg') }}" alt="" width="290" height="219"/></a></div>
            <div class="col-6 col-sm-4 col-lg-3"><a class="thumbnail-minimal" href="{{ asset('site/images/uploads/instagram/Babyblossom-' ~ category.slug ~ '-3.jpg') }}" data-lightgallery="item"><img src="{{ asset('site/images/uploads/instagram-sm/bblossom-' ~ category.slug ~ '-3.jpg') }}" alt="" width="290" height="219"/></a></div>
            <div class="col-6 col-sm-4 col-lg-3"><a class="thumbnail-minimal" href="{{ asset('site/images/uploads/instagram/Babyblossom-' ~ category.slug ~ '-4.jpg') }}" data-lightgallery="item"><img src="{{ asset('site/images/uploads/instagram-sm/bblossom-' ~ category.slug ~ '-4.jpg') }}" alt="" width="290" height="219"/></a></div>
            <div class="col-6 col-sm-4 col-lg-3"><a class="thumbnail-minimal" href="{{ asset('site/images/uploads/instagram/Babyblossom-' ~ category.slug ~ '-5.jpg') }}" data-lightgallery="item"><img src="{{ asset('site/images/uploads/instagram-sm/bblossom-' ~ category.slug ~ '-5.jpg') }}" alt="" width="290" height="219"/></a></div>
            <div class="col-6 col-sm-4 col-lg-3"><a class="thumbnail-minimal" href="{{ asset('site/images/uploads/instagram/Babyblossom-' ~ category.slug ~ '-6.jpg') }}" data-lightgallery="item"><img src="{{ asset('site/images/uploads/instagram-sm/bblossom-' ~ category.slug ~ '-6.jpg') }}" alt="" width="290" height="219"/></a></div>
            <div class="col-6 col-sm-4 col-lg-3"><a class="thumbnail-minimal" href="{{ asset('site/images/uploads/instagram/Babyblossom-' ~ category.slug ~ '-7.jpg') }}" data-lightgallery="item"><img src="{{ asset('site/images/uploads/instagram-sm/bblossom-' ~ category.slug ~ '-7.jpg') }}" alt="" width="290" height="219"/></a></div>
            <div class="col-sm-4 col-lg-3 d-flex align-items-center justify-content-center">
              <div class="box-info-rose-2">
                <p class="box-info-rose-text">Instagram</p><a class="link-classic link-primary" href="#">@babyblossomke</a>
              </div>
            </div>
          </div>
        </div>
      </section> 

{% endblock %}

{% block javascripts_bottom %}


<script>
    $(document).ready(function () {
        $('button[id^="cartProd_"]').on('click', function () {
            var formId = $(this).closest('form').attr('id');
            var productId = formId.split('-')[1];
            var clickedButton = $('#' + formId + ' button').attr('name');
            console.log(formId);
            console.log(productId);
            console.log(clickedButton);
            $.ajax({
                type: 'POST',
                url: "{{path('add_product_to_cart_index') }}", // Replace with your actual controller action route
                data: {
                    product_id: productId,
                    clickedButton: clickedButton
                },
                success: function (response) {
                    console.log(response);
                    // Handle the response, update the cart UI, etc.
                    if (response.status === 'success') {
                        // Update total products and total price in your UI
                        window.location.href = '/cart';
                    }
                },
                error: function (error) {
                    console.error(error);
                }
            });
        });
    });
</script>


{% endblock %}

templates/default/faq.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} 
{{ leogout_seo() }} 
<style>
    h2{
        font-size: 26px;
        text-transform: capitalize;
        
    }
    p, ul, ol, div{
      font-size:16px!important;
      line-height:1.5;
      text-align: left;
    }

    ul, ol {
        list-style-type: disc;
    }
    
</style>
{% endblock %}
{% block page %}
      <section class="breadcrumbs-custom">
        <div class="parallax-container" data-parallax-img="/site/images/baby-blossom-all-products-banner.jpg">
          <div class="breadcrumbs-custom-body parallax-content">
            <div class="container">
              <h1 class="breadcrumbs-custom-title">Frequenty Asked Questionss</h1>
            </div>
          </div>
        </div>
        <div class="breadcrumbs-custom-footer">
          <div class="container">
            <ul class="breadcrumbs-custom-path">
              <li><a href="{{ path('app_default') }}">Home</a></li>
              <li><a href="#">Pages</a></li>
              <li class="active">FAQ</li>
            </ul>
          </div>
        </div>
      </section>
      <!-- Frequenty Asked Questionss-->
      <section class="section section-xxl bg-default text-md-left">
        <div class="container">
          <div class="row">
            <div class="col-lg-10 col-xl-8">
              <!-- Terms list-->
              {{ faq.content|replace({'.' : '.<br><br>'})|raw }}
            </div>
          </div>
        </div>
      </section>
{% endblock %}      

templates/default/profile.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} {{ leogout_seo() }} {% endblock %}
{% block page %}

{% endblock %}

templates/default/test2.html.twig
{{dump(statements)}}